import express from "express";
import tenantRouter from "./tenantRoutes.js";
import authRouter from "./auth.js";
import superadminAuthRouter from "./superadminAuth.js";
import superadminRouter from "./superadminRoutes.js";
import tenantAdminRouter from "./tenantAdminRoutes.js";
import legacyAuthRouter from "./authRoutes.js";
import planRouter from "./planRoutes.js";
import organizationTypeRouter from "./organizationTypeRoutes.js";
import courseRouter from "./courseRoutes.js";
import aiRouter from "./aiRoutes.js";
import assignmentRouter from "./assignmentRoutes.js";
import userRouter from "./userRoutes.js";
import enrollmentRouter from "./enrollmentRoutes.js";
import progressRouter from "./progressRoutes.js";
import quizRouter from "./quizRoutes.js";
import ownershipTransferRouter from "./ownershipTransferRoutes.js";
import roleRouter from "./roleRoutes.js";
import masterDataRouter from "./masterDataRoutes.js";
const router = express.Router();

router.use("/auth", authRouter);
router.use("/auth/legacy", legacyAuthRouter);
router.use("/superadmin/auth", superadminAuthRouter);
router.use("/superadmin", superadminRouter);
router.use("/tenant-admin", tenantAdminRouter);
router.use("/users", userRouter);
router.use("/roles", roleRouter);
router.use("/master-data", masterDataRouter);
router.use("/enrollments", enrollmentRouter);
router.use("/progress", progressRouter);
router.use("/quizzes", quizRouter);
router.use("/tenants", tenantRouter);
router.use("/plans", planRouter);
router.use("/organization-types", organizationTypeRouter);
router.use("/courses", courseRouter);
router.use("/ai", aiRouter);
router.use("/assignments", assignmentRouter);
router.use("/ownership-transfers", ownershipTransferRouter);

export default router;

